name: bundesposts_scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=25.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - comm=0.2.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libedit=3.1.20250104
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libopenblas=0.3.28
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.4.1
  - outcome=1.3.0.post0
  - packaging=24.2
  - pandas=2.0.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytz=2025.1
  - pyzmq=26.2.1
  - readline=8.2
  - selenium=4.10.0
  - setuptools=75.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - trio=0.28.0
  - trio-websocket=0.11.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wsproto=1.2.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - charset-normalizer==3.4.1
      - filelock==3.17.0
      - python-magic==0.4.27
      - requests==2.32.3
      - webdriver-manager==4.0.1
